---
  - name: Install ELK
    hosts: elk
    become: true
    tasks: 
    - name: Increase system memory available
      ansible.posix.sysctl:
        name: vm.max_map_count
        value: '262144'
      
    - name: Update apt
      apt:
        update_cache: yes

    - name: Install docker
      apt: 
        name: docker.io
        state: present

    - name: Install python3-pip
      apt: 
        name: python3-pip
        state: present

    - name: Install docker for Python
      pip:
        name: docker

    - name: Install cyberxsecurity-dvwa
      docker_container:
        name: ELK-stack
        image: sebp/elk:761
        state: started
        restart_policy: always
        published_ports: 
          - 5601:5601
          - 9200:9200
          - 5044:5044

    - name: Enable docker service
      systemd: 
        name: docker
        enabled: yes

